name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  flutter_version: '3.41.6'
  flutter_channel: 'stable'

jobs:
  flutter_format:
    name: Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
          cache: true
      - name: Generate required code
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
      - name: Run flutter test
        run: flutter test
